services:
  postgres:
    image: postgres:16-alpine
    container_name: cryptotax-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cryptotax_user
      - POSTGRES_PASSWORD=cryptotax_pass
      - POSTGRES_DB=cryptotax_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

