spring.application.name=crypto-tax-pln
nbp.api.host=https://api.nbp.pl
nbp.api.endpoint=${nbp.api.host}/api/exchangerates/rates/a/
nbp.api.url-template=${nbp.api.endpoint}/{currency}/{date}/?format=json
nbp.api.max-attempts=10

spring.datasource.url=jdbc:postgresql://localhost:5432/cryptotax_db
spring.datasource.username=cryptotax_user
spring.datasource.password=cryptotax_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
