### Test wysyłania pliku CSV do importu transakcji
POST http://localhost:8080/api/v1/transactions/import
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test-transactions.csv"
Content-Type: text/csv

< ./test-transactions.csv
--WebAppBoundary--